# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: heartbeat_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_pb2 as message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='heartbeat_service.proto',
  package='ai_flow',
  syntax='proto3',
  serialized_options=b'\n\027org.aiflow.client.protoZ\010/ai_flow\210\001\001\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17heartbeat_service.proto\x12\x07\x61i_flow\x1a\rmessage.proto\"]\n\x10HeartbeatRequest\x12\x1d\n\x15workflow_execution_id\x18\x01 \x01(\x03\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x03\x32T\n\x10HeartbeatService\x12@\n\x0esend_heartbeat\x12\x19.ai_flow.HeartbeatRequest\x1a\x11.ai_flow.Response\"\x00\x42)\n\x17org.aiflow.client.protoZ\x08/ai_flow\x88\x01\x01\x90\x01\x01\x62\x06proto3'
  ,
  dependencies=[message__pb2.DESCRIPTOR,])




_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='ai_flow.HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflow_execution_id', full_name='ai_flow.HeartbeatRequest.workflow_execution_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='task_name', full_name='ai_flow.HeartbeatRequest.task_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='ai_flow.HeartbeatRequest.sequence_number', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'heartbeat_service_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)


DESCRIPTOR._options = None

_HEARTBEATSERVICE = _descriptor.ServiceDescriptor(
  name='HeartbeatService',
  full_name='ai_flow.HeartbeatService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=146,
  serialized_end=230,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_heartbeat',
    full_name='ai_flow.HeartbeatService.send_heartbeat',
    index=0,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=message__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEARTBEATSERVICE)

DESCRIPTOR.services_by_name['HeartbeatService'] = _HEARTBEATSERVICE

HeartbeatService = service_reflection.GeneratedServiceType('HeartbeatService', (_service.Service,), dict(
  DESCRIPTOR = _HEARTBEATSERVICE,
  __module__ = 'heartbeat_service_pb2'
  ))

HeartbeatService_Stub = service_reflection.GeneratedServiceStubType('HeartbeatService_Stub', (HeartbeatService,), dict(
  DESCRIPTOR = _HEARTBEATSERVICE,
  __module__ = 'heartbeat_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
