# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import heartbeat_service_pb2 as heartbeat__service__pb2
from . import message_pb2 as message__pb2


class HeartbeatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_heartbeat = channel.unary_unary(
                '/ai_flow.HeartbeatService/send_heartbeat',
                request_serializer=heartbeat__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )


class HeartbeatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartbeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.send_heartbeat,
                    request_deserializer=heartbeat__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_flow.HeartbeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HeartbeatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai_flow.HeartbeatService/send_heartbeat',
            heartbeat__service__pb2.HeartbeatRequest.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
