# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import message_pb2 as message__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler_service.proto',
  package='ai_flow',
  syntax='proto3',
  serialized_options=b'\n\027org.aiflow.client.protoZ\010/ai_flow\210\001\001\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17scheduler_service.proto\x12\x07\x61i_flow\x1a\rmessage.proto\x1a\x1cgoogle/api/annotations.proto\"\x87\x01\n\x15UpdateWorkflowRequest\x12/\n\nidentifier\x18\x01 \x01(\x0b\x32\x1b.ai_flow.WorkflowIdentifier\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x18\n\x10pickled_workflow\x18\x03 \x01(\x0c\x12\x12\n\nis_enabled\x18\x04 \x01(\x08\">\n\x11WorkflowListProto\x12)\n\tworkflows\x18\x01 \x03(\x0b\x32\x16.ai_flow.WorkflowProto\"L\n\x14ListWorkflowsRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x03\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x32\xd7\x06\n\x10SchedulerService\x12x\n\x16startWorkflowExecution\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\".\x82\xd3\xe4\x93\x02(\"#/scheduler/workflow_execution/start:\x01*\x12[\n\x0b\x61\x64\x64Workflow\x12\x16.ai_flow.WorkflowProto\x1a\x11.ai_flow.Response\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/metadata/workflow/add:\x01*\x12i\n\x0eupdateWorkflow\x12\x1e.ai_flow.UpdateWorkflowRequest\x1a\x11.ai_flow.Response\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/metadata/workflow/update:\x01*\x12`\n\x0bgetWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/metadata/workflow/get:\x01*\x12\x66\n\x0e\x64\x65leteWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/metadata/workflow/delete:\x01*\x12h\n\x0f\x64isableWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"%\x82\xd3\xe4\x93\x02\x1f\"\x1a/metadata/workflow/disable:\x01*\x12\x66\n\x0e\x65nableWorkflow\x12\x1b.ai_flow.WorkflowIdentifier\x1a\x11.ai_flow.Response\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/metadata/workflow/enable:\x01*\x12\x65\n\rlistWorkflows\x12\x1d.ai_flow.ListWorkflowsRequest\x1a\x11.ai_flow.Response\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/metadata/workflow/list:\x01*B)\n\x17org.aiflow.client.protoZ\x08/ai_flow\x88\x01\x01\x90\x01\x01\x62\x06proto3'
  ,
  dependencies=[message__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_UPDATEWORKFLOWREQUEST = _descriptor.Descriptor(
  name='UpdateWorkflowRequest',
  full_name='ai_flow.UpdateWorkflowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='ai_flow.UpdateWorkflowRequest.identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='ai_flow.UpdateWorkflowRequest.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pickled_workflow', full_name='ai_flow.UpdateWorkflowRequest.pickled_workflow', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='ai_flow.UpdateWorkflowRequest.is_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=217,
)


_WORKFLOWLISTPROTO = _descriptor.Descriptor(
  name='WorkflowListProto',
  full_name='ai_flow.WorkflowListProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workflows', full_name='ai_flow.WorkflowListProto.workflows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=281,
)


_LISTWORKFLOWSREQUEST = _descriptor.Descriptor(
  name='ListWorkflowsRequest',
  full_name='ai_flow.ListWorkflowsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ai_flow.ListWorkflowsRequest.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ai_flow.ListWorkflowsRequest.page_size', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ai_flow.ListWorkflowsRequest.offset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=359,
)

_UPDATEWORKFLOWREQUEST.fields_by_name['identifier'].message_type = message__pb2._WORKFLOWIDENTIFIER
_WORKFLOWLISTPROTO.fields_by_name['workflows'].message_type = message__pb2._WORKFLOWPROTO
DESCRIPTOR.message_types_by_name['UpdateWorkflowRequest'] = _UPDATEWORKFLOWREQUEST
DESCRIPTOR.message_types_by_name['WorkflowListProto'] = _WORKFLOWLISTPROTO
DESCRIPTOR.message_types_by_name['ListWorkflowsRequest'] = _LISTWORKFLOWSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateWorkflowRequest = _reflection.GeneratedProtocolMessageType('UpdateWorkflowRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEWORKFLOWREQUEST,
  '__module__' : 'scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.UpdateWorkflowRequest)
  })
_sym_db.RegisterMessage(UpdateWorkflowRequest)

WorkflowListProto = _reflection.GeneratedProtocolMessageType('WorkflowListProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWLISTPROTO,
  '__module__' : 'scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.WorkflowListProto)
  })
_sym_db.RegisterMessage(WorkflowListProto)

ListWorkflowsRequest = _reflection.GeneratedProtocolMessageType('ListWorkflowsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTWORKFLOWSREQUEST,
  '__module__' : 'scheduler_service_pb2'
  # @@protoc_insertion_point(class_scope:ai_flow.ListWorkflowsRequest)
  })
_sym_db.RegisterMessage(ListWorkflowsRequest)


DESCRIPTOR._options = None

_SCHEDULERSERVICE = _descriptor.ServiceDescriptor(
  name='SchedulerService',
  full_name='ai_flow.SchedulerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=362,
  serialized_end=1217,
  methods=[
  _descriptor.MethodDescriptor(
    name='startWorkflowExecution',
    full_name='ai_flow.SchedulerService.startWorkflowExecution',
    index=0,
    containing_service=None,
    input_type=message__pb2._WORKFLOWIDENTIFIER,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002(\"#/scheduler/workflow_execution/start:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='addWorkflow',
    full_name='ai_flow.SchedulerService.addWorkflow',
    index=1,
    containing_service=None,
    input_type=message__pb2._WORKFLOWPROTO,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\033\"\026/metadata/workflow/add:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateWorkflow',
    full_name='ai_flow.SchedulerService.updateWorkflow',
    index=2,
    containing_service=None,
    input_type=_UPDATEWORKFLOWREQUEST,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\036\"\031/metadata/workflow/update:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getWorkflow',
    full_name='ai_flow.SchedulerService.getWorkflow',
    index=3,
    containing_service=None,
    input_type=message__pb2._WORKFLOWIDENTIFIER,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\033\"\026/metadata/workflow/get:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteWorkflow',
    full_name='ai_flow.SchedulerService.deleteWorkflow',
    index=4,
    containing_service=None,
    input_type=message__pb2._WORKFLOWIDENTIFIER,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\036\"\031/metadata/workflow/delete:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disableWorkflow',
    full_name='ai_flow.SchedulerService.disableWorkflow',
    index=5,
    containing_service=None,
    input_type=message__pb2._WORKFLOWIDENTIFIER,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\037\"\032/metadata/workflow/disable:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='enableWorkflow',
    full_name='ai_flow.SchedulerService.enableWorkflow',
    index=6,
    containing_service=None,
    input_type=message__pb2._WORKFLOWIDENTIFIER,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\036\"\031/metadata/workflow/enable:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='listWorkflows',
    full_name='ai_flow.SchedulerService.listWorkflows',
    index=7,
    containing_service=None,
    input_type=_LISTWORKFLOWSREQUEST,
    output_type=message__pb2._RESPONSE,
    serialized_options=b'\202\323\344\223\002\034\"\027/metadata/workflow/list:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULERSERVICE)

DESCRIPTOR.services_by_name['SchedulerService'] = _SCHEDULERSERVICE

SchedulerService = service_reflection.GeneratedServiceType('SchedulerService', (_service.Service,), dict(
  DESCRIPTOR = _SCHEDULERSERVICE,
  __module__ = 'scheduler_service_pb2'
  ))

SchedulerService_Stub = service_reflection.GeneratedServiceStubType('SchedulerService_Stub', (SchedulerService,), dict(
  DESCRIPTOR = _SCHEDULERSERVICE,
  __module__ = 'scheduler_service_pb2'
  ))


# @@protoc_insertion_point(module_scope)
